### ISSUE TITLE
[ml] Individual scores are too sensitive to a few ratings only

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#1065]
As observed by Louis and myself, some top videos in contributors' recommendations have only been scored once or twice. In particular, videos that have only been scored as better than (bad) alternatives tend to have too high scores.

To fix this, we propose to fix the value of a hyperparameter, namely, the weight of the regularization in contributor's brute score inference.
<img width="742" alt="Screen Shot 2022-07-20 at 11 06 55" src="https://user-images.githubusercontent.com/10453308/180016936-75c6cf6c-4fb7-4bfb-9b19-9e3b05d9ac0f.png">

For more context, please refer to the Overleaf algorithm description paper, page 15: https://www.overleaf.com/project/5f44dd8e84c8540001bf1552

**Comment by amatissart** [comment]
The implementation still uses $\alpha^{contributor}_{prior} = 0.01$

https://github.com/tournesol-app/tournesol/blob/a8ad2805c9b5c18bd763bc6a87b4cf0191a373c2/backend/ml/mehestan/individual.py#L7

As discussed in https://arxiv.org/abs/2211.01179 (in Supplementary Material - Section B), this value  seems too low. However the process described to evaluate this parameter based on contributor scores is divergent when repeated successively. 

We need to keep in mind that updating this parameter will have cascading consequences not inly on the distributions of individual scores, but also on the poll scaling, hence on the distribution of Tournesol scores. In particular, this will change the maximum score that a video can reach after being compared by a single contributor. 


### Impact of $\alpha$ on scores distribution
_Evaluated on production dataset (2023-01-02)_

||Global scores distribution<br><em>(Tournesol scores)</em>| Individual scores distribution<br><em>on the same scale</em> `]-100,100[`<br><em>(after scalings: individual AND poll)</em>|
|-|-|-|
|$\alpha = 0.01$<br>**(current value in production)**|![1_alpha_0 01](https://user-images.githubusercontent.com/4726554/210269929-6a2a964c-c863-411f-a478-63465870a953.png)|![image](https://user-images.githubusercontent.com/4726554/210269972-efeb780c-cd7d-4eb3-999f-5ac66f8cc841.png)
|$\alpha = 0.1$|![2_alpha_0 1](https://user-images.githubusercontent.com/4726554/210270035-394b692a-f732-494b-8515-7f7c82f038da.png)|![2_alpha_0 1_indiv](https://user-images.githubusercontent.com/4726554/210270053-8ebad850-bc65-4526-b373-446d07525e24.png)
|$\alpha = 0.3$|![3_alpha_0 3](https://user-images.githubusercontent.com/4726554/210270080-d6451638-a32d-40e6-8534-31fcd190003c.png)|![3_alpha_0 3_indiv](https://user-images.githubusercontent.com/4726554/210270084-25a68817-6c6f-4c70-8565-1a1c2a60823c.png)
|$\alpha = 1.0$|![4_alpha_1 0](https://user-images.githubusercontent.com/4726554/210270137-599b92a8-70ca-46a9-98d3-ebd0259f1a89.png)|![4_alpha_1 0_indiv](https://user-images.githubusercontent.com/4726554/210270147-a0558945-ad3e-4286-97b1-54cfbdc71b97.png)

### Observations:
1. The distribution of scaled individual scores appear quite polarized, even with higher values for $\alpha$. I think that's actually expected due to how the poll scaling transformation is calibrated on Tournesol scores, which are regularized by design. (e.g 50 is the top 1% regularized median on the global scale, but is not so uncommon on the individual scale). But maybe the effect is still counter-intuitive when used in the UI? 

2. As expected, with higher values of $\alpha$, the distribution of Tournesol scores is more scattered around zero. And the maximum score reached by a video with a single contributor is also higher:  
~18 with $\alpha=0.01$ and ~32 with $\alpha=1.0$

**Comment by amatissart** [comment]
As the distributions of individual scores looked too polarized, we decided to adapt the definition of the poll scaling.
The current scale is defined such as the top 1% of scored videos have a score >= 50.
Following our discussion, I suggest to use this new definition: the top 25% of videos rated by at least 4 contibutors should have a score >= 25.

### Distributions with different values of $\alpha$

_note that the color scheme for individual scores have changed: the colors represent the number of comparisons per rating, i.e per pair (user, video)_

||Global scores distribution<br><em>(Tournesol scores)</em>| Individual scores distribution<br><em>on the same scale</em> `]-100,100[`<br><em>(after scalings: individual AND poll)</em>|
|-|-|-|
|$\alpha = 0.01$<br>**Reference**<br>(current value in production, poll_scaling unchanged)|![ref_global_0 01](https://user-images.githubusercontent.com/4726554/213402982-721a274d-3536-4a3a-b81a-6453e05d4239.png)|![ref_indiv_0 01](https://user-images.githubusercontent.com/4726554/213403003-524767f6-f289-46f0-9cf7-789cdcc791d6.png)
|$\alpha = 0.01$<br>**New poll scaling**|![s4_75_global_0 01](https://user-images.githubusercontent.com/4726554/213403542-17a79fe3-8214-4d7b-9a06-19e55aa5aeb3.png)|![s4_75_indiv_0 01](https://user-images.githubusercontent.com/4726554/213403565-7805210e-5357-4270-ad38-8672be9482d7.png)
|$\alpha = 0.1$<br>**New poll scaling**|![s4_75_global_0 1](https://user-images.githubusercontent.com/4726554/213403682-7b26f3eb-3414-4122-a230-640e99e58894.png)|![s4_75_indiv_0 1](https://user-images.githubusercontent.com/4726554/213403695-812f3195-f146-4de7-b97b-42928bf00b09.png)
|$\alpha = 0.5$<br>**New poll scaling**|![s4_75_global_0 5](https://user-images.githubusercontent.com/4726554/213403864-2b5732fd-810c-41d6-8388-958216d373a5.png)|![s4_75_indiv_0 5](https://user-images.githubusercontent.com/4726554/213403882-eb7769d4-3311-44b0-ac77-f2c3f590b574.png)
|$\alpha = 1.0$<br>**New poll scaling**|![s4_75_global_1 0](https://user-images.githubusercontent.com/4726554/213404185-183af9c5-9a7d-4db2-99eb-3f9c0303f14b.png)|![s4_75_indiv_1 0](https://user-images.githubusercontent.com/4726554/213404205-7e6ce327-0291-4dc5-b95a-9650bcbff169.png)
|$\alpha = 2.0$<br>**New poll scaling**|![s4_75_global_2 0](https://user-images.githubusercontent.com/4726554/213404371-390f1ac3-001b-4c02-b6ea-e56ef29a5c1e.png)|![s4_75_indiv_2 0](https://user-images.githubusercontent.com/4726554/213404388-9a54b8ab-795d-49a8-b6cd-f977e1d4ae3e.png)
