### ISSUE TITLE
Rejected and Pending domains are not shown anymore

### ISSUE THREAD

**Issue by petersg83** [tournesol-app/tournesol#108]
I can't see anymore the Rejected and Pending domains on this page : https://tournesol.app/email_domains

I wanted to check if my email was in pending status or if it has been rejected.

**Comment by lenhoanglnh** [comment]
We were concerned that the list of rejected/pending domains was leaking private information.
Many domains are associated with an individual.

But maybe we should have this list up there. What do you think?

(you should be able to see the status of your domain in the Tournesol home page, if it says "currently not trusted" it means that it has been rejected. Otherwise, it should say "We are currently assessing the trustworthiness of the email domain")

**Comment by petersg83** [comment]
I understand your concerns. I agree that it may leak some private information. Even the accepted domains leak some.

Thank you for the tip, my email seems trusted ! For the need I had, a clear interface that says that my email is trusted would be enough I think.

For future plans, I would find interesting to have some analytics on the contributors of the platform though. In a way, the contributors are now the real data source the AI is fed with, which may contain some biases too.

**Comment by lfaucon** [comment]
Done
