### ISSUE TITLE
Add social media links on the homepage

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#117]
Something like that, somewhere on the homepage.

![image](https://user-images.githubusercontent.com/53896963/118676267-8b7f9280-b7fb-11eb-944b-4796fe96d817.png)

**Comment by GresilleSiffle** [comment]
Hi @aidanjungo 

One solution could be to add the icons in the yellow `<AppBar>` present in the top of the screen, so they will always be visible. Like on this site : https://material-ui.com

I don't know if it's really appropriate because I often see this kind of bars used to provide functionality related to the application like accessing my profile, see the notifications or the current pending actions (like the current number of " rate later " videos). Actions that keep the user on the same web site.

Nevertheless, it's an option : )

**Comment by GresilleSiffle** [comment]
A classic implementation with standard Material UI components, without any CSS added looks like this.


![appbar_socialmedia](https://user-images.githubusercontent.com/39056254/118887324-7dfd0200-b8fa-11eb-8cb8-ffefd3ee1402.png)

**Comment by aidanjungo** [comment]
Yes, it looks nice to me. If you want to work on the implementation of that, feel free 😃

**Comment by sergeivolodin** [comment]
@aidanjungo please close if it looks good (live on tournesol.app in ~10mins)
