### ISSUE TITLE
[infra] clarify our secrets' back up strategy

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1239]
### Context

The back end's secrets are saved in one specific file of our production virtual machine. They are vulnerable to different kind of losses like:
- **(a)** a templating error during the deployment can erase the secrets (this happened recently)
- **(b)** a VM made non-accessible can prevent us to retrieve the secrets

### Proposition

To address the issue **(a)**, we could update our deployment recipe to not directly erase the previous secrets file, but to create a copy before. We can then keep a certain amount of copy before erasing them. In case of error during the deployment, this will allow us to quickly fix the back end by manually restoring the previous secrets file. The file mode of the copies should be 600.

To adresss the issue **(b)**, let's talk about it "in person".

**Comment by amatissart** [comment]
The solution for **(a)** could be as simple as setting the "[backup" parameter](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#parameter-backup) in the Ansible task, when copying the settings file: https://github.com/tournesol-app/tournesol/blob/ccc0e66f03a6c5608fe5e99ba8509718ba9fda7d/infra/ansible/roles/django/tasks/main.yml#L36-L41

**Comment by amatissart** [comment]
Regarding **(a)**, old versions of the settings file are now persisted (#1258)

Regarding **(b)**, the keepass file is the reference to be updated first when a new secret is created/updated. Ideally we may prefer to use this keepass file (or a similar vault) as the single source of truth on deploy, instead of retrieving secrets from the existing environments. But that does not seem to be a very high priority.
