### ISSUE TITLE
[extension] fix: extension buttons break responsive layout on medium screens on Youtube. 

### ISSUE THREAD

**Issue by raphaelp-github** [tournesol-app/tournesol#1319]
The like button is superimposed on the subscribe button.

![image](https://user-images.githubusercontent.com/34160362/215267810-ebcf9a91-3883-4a19-8733-743b27c4860a.png)

Screen size : 14"

Thank's

**Comment by lfaucon** [comment]
Thanks for the reporting!

**Comment by abhiram11** [comment]
We can remove the text `Rate Later` and `Rate Now` and just keep the icons there, but that would require manipulation of text nodes which is a bit tricky.

I can try to implement it, I'll wrap the text node with a `span` or something and then try to hide the text only for screen sizes between ~ sm:md (`656px to 900px` would do)

**Comment by abhiram11** [comment]
Alternatively, adding this snippet below in addRateButtons.css gives the below output, it still needs more specificity.

```
@media (min-width: 656px) and (max-width: 900px) {
  button.tournesol-rate-button {
    font-size: 0;
  }
}
```
![image](https://user-images.githubusercontent.com/20269286/221615388-29ea01ba-cb16-4692-b42a-94d9ba3e80c9.png)

**Comment by lfaucon** [comment]
Removing the text and keeping the icons looks good!

The layout issue occurs also on screens of width 1100px:

![Screenshot 2023-02-27 at 21 30 06](https://user-images.githubusercontent.com/8818081/221678534-aa37da6b-71aa-4a66-a2a0-767ef58f08e8.png)

It seems to start occuring from about 1250px until 1000px , then from 999px the layout changes and it looks ok again (see screenshot)

![Screenshot 2023-02-27 at 21 33 14](https://user-images.githubusercontent.com/8818081/221679348-646b5d79-a818-435a-999b-d11984e383da.png)

Then it starts to look bad around 850px until 639px, then the layout changes again at 638px:

![Screenshot 2023-02-27 at 21 36 51](https://user-images.githubusercontent.com/8818081/221680307-ee64fd2f-b6c2-49f9-b122-c790d00a5188.png)


As a conclusion I woulc propose hiding the text for the intervals 1250px until 1000px and 850px until 639px, but I'm not completely sure that this generalises to everyone, and it may also break with future versions of Youtube.

Because it is only a small piece of code, I'm happy with it.

If you want to open a PR @abhiram11 that will be very welcomed 👍

**Comment by abhiram11** [comment]
I agree with this approach! I have opened a PR for the same which seems a great temporary fix for this issue. Let me know if there's any changes to be made or if it looks good.

**Comment by GresilleSiffle** [comment]
A first PR has been merged, let's check if some screen sizes are still problematic.
