### ISSUE TITLE
Error in uncertainty of scaling-calibration contributors' scores

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#1338]
As pointed out by @glerzing, there is an inconsistency in the algorithms I proposed, when computing the uncertainties on raw scores. In particular, for some unjustified reason, scaling-calibration and non-scaling-calibration contributors are not handled the same way.

The fix is to this line: https://github.com/tournesol-app/tournesol/blob/main/backend/ml/mehestan/global_scores.py#L274
And it should be more like this: https://github.com/tournesol-app/tournesol/blob/main/backend/ml/mehestan/global_scores.py#L298

See Section E.1.1 in the Overleaf: https://www.overleaf.com/project/63d63d642537a23c46fb1775

**Comment by amatissart** [comment]
Does this mean that we want use `QrMed` and `QrUnc` instead of `BrMean`, to use the exact same implementation for both scaling-calibration and non-scaling-calibration users?

$\Delta s$ and $\Delta \tau$ are currently not computed at all for scaling-calibration users. For reference:

https://github.com/tournesol-app/tournesol/blob/e109ac73010ddf710a44619db405622e3a4e9be6/backend/ml/mehestan/global_scores.py#L137-L150
