### ISSUE TITLE
[bug] user's preferences are not retrieved after login

### ISSUE THREAD

**Issue by ShinseiNova** [tournesol-app/tournesol#1554]
User's preferences are well stored but not retrieved after the user logs back in.
We can get them by refreshing the page.

That means there is an effect responsible for saving the API return in the store which is not properly triggered on login.

**Comment by GresilleSiffle** [comment]
According to what I see in Redux, the `fetchUserSettings` promise is rejected because the API answers with an HTTP 401 response. As a consequence, the user's preferences are not retrieved, the store is empty, and the preferences form displays the default value for each setting.

The  `fetchUserSettings` may be called "too soon" before the authentication token is retrieved. We need to be sure that we retrieve the user's settings when the login process is finished.

(in case we are not able to fix the problem easily, we could use a Redux middleware to trigger `fetchUserSettings` after the successful login reducer)
