### ISSUE TITLE
[front] feat: Add option to exclude rated entities in recommendation page

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1563]
- [x] Step 1: Fix issue with caching of the recommendation route on the backend (see discussion below)
#1702

- [ ] Step 2: Set the argument exclude compared entities to True in the frontend's recommendations
#1703

**Comment by GresilleSiffle** [comment]
As discussed with @lfaucon , we suspect that the API is not working properly when the query parameter `exclude_compared_entities` is provided.

Because the responses of the recommendations route are cached, what happens when a user asks the recommendations with `exclude_compared_entities=true`? Do they receive the cached response corresponding to another user?

We want to investigate this first before developing a new UI in the front end.

**Comment by lfaucon** [comment]
Ah, yes... We totally overlooked skipping the cache when `exclude_compared_entities=true`. Should be a small fix on the backend, right?

**Comment by GresilleSiffle** [comment]
I think we have several alternatives here, we talked about them with @amatissart (but I'm not sure I remember each detail):

- maintaining a list of private filters, when detected, the results are not cached to avoid any leak
- maintaining a list of private filters, when detected, the results are cached per user to keep the view efficient

It shouldn't be too difficult, but we may need to write a new cache decorator like `cache_page_no_i18n`
