### ISSUE TITLE
[ext] bug: Unnecessary alert and iframe stuck on Home Page

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1779]
Regularly (when auth is expired?) an alert to log in again appears on Youtube to request loging in again. Then it opens an iframe that is stuck on the Home page of Tournesol.

**Comment by GresilleSiffle** [comment]
There are several issues with the browser extension:

(a) There is an alert displayed when the YouTube page is loading. This alert is not required. Instead, we can try to refresh the user's access token in the background or display a login iframe when needed.

(b) Some extension requests to the API can fail when the YT page starts loading. This is because the script responsible of updating the extension token is run after the YT page has finished loading, causing all previous requests to fail if the token of the extension is expired or null.

Nevertheless this shouldn't display any login iframe and all following page reload should work.
