### ISSUE TITLE
[ext][back] bug: "Watch on Tounesol" button doesn't work when the video is not in the database AND the user is disconnected

### ISSUE THREAD

**Issue by maximedrouhin** [tournesol-app/tournesol#1904]
<img width="773" alt="image" src="https://github.com/tournesol-app/tournesol/assets/52411229/abe7112e-c8c6-4896-9158-b84874fab056">

The new "Watch on Tournesol" button displayed under YouTube videos works fine for videos that are already in the Tournesol database. It also works for users who are disconnected from Tournesol. But when the user is disconnected AND the video is not in the Tournesol database, a "Not found" error is displayed.
<img width="916" alt="image" src="https://github.com/tournesol-app/tournesol/assets/52411229/05d845dd-1264-48dd-9d07-04751df3d97e">

You can use this random YouTube video for testing, as it's likely not in the Tournesol database: https://perchance.org/youtube-video

**Comment by GresilleSiffle** [comment]
Confirmed on `main` at 032419a3be8e741214f5cc767940f29f36acc0d0

The view responsible of creating new videos in the database is limited to authenticated users. This limit may have been configured to limit the number of request made to the YouTube API.

A possible short term fix could be to hide the Watch on Tournesol button for anonymous users.

**Comment by GresilleSiffle** [comment]
About the option (a)

If we make public our endpoint calling the YT API, it will be easy for malicious users and robots to completely deplete our YT API credits every day. Adding a throttle rate in the Tournesol API might look like a good idea to keep our credits safe, nevertheless I think it simply moves the problem from one place to another. Once the throttle limit is reached, all anonymous users using the Watch on Tournesol button on new video will receive a HTTP 429 Too Many Request from the API. So instead of depleting the YT API credits, it will deplete the number of possible use of our API.

**Comment by GresilleSiffle** [comment]
The button Watch on Tournesol should not appear anymore for anonymous users.
