### ISSUE TITLE
Blank page when cookies are blocked

### ISSUE THREAD

**Issue by ipnoz** [tournesol-app/tournesol#2013]
This is a common problem that I can encounter on several websites :

I block by default all cookies with Firefox, and the Tournesol.app simply display a blank page, because probably of CORS...

It is a pity that users cannot access this particular website without cookies

**Comment by ipnoz** [comment]
![Capture d’écran_2024-09-15_11-51-55](https://github.com/user-attachments/assets/5556334f-df8e-474e-abd5-ef813631b3f7)

**Comment by amatissart** [comment]
Hi @ipnoz, thanks for your feedback.

HTTP cookies should not be necessary to visit tournesol.app, but blocking "cookies" on Firefox will actually cause other kinds of persistent storage to be disabled, including ` localStorage`. And that's why you can see an exception "The operation is insecure" in the console in this case: the access to the `localStorage` has been rejected with a security error.

Tournesol relies on the `localStorage` for several reasons, for example to persist some preferences for non-authenticated users. Although we had a few checks in place to anticipate the case when `localStorage` would not be available, this error was not handled properly.

I tried to fix that in PR #2018 (still under review). That should avoid this error and allow to visit the website with "cookies" blocked on Firefox, even if some minor features that require to persist some data on the browser may not behave as expected. I will keep you updated when the fix is deployed.

Note that the error about CORS is unrelated: it's about requests to our [Plausible](https://plausible.io/open-source-website-analytics) instance, the tool we are using for privacy-preserving analytics on Tournesol. It's probably blocked on your configuration, but that's not an issue to access the website.
