### ISSUE TITLE
Use natural language preferences

### ISSUE THREAD

**Issue by sergia-ch** [tournesol-app/tournesol#33]
As in early social networks, we will have interest groups -- you enter preferences in natural language (for example, "I like baseball videos" or "I like videos about the epiphenomenal view on consciousness with information being the way to merge mind and matter philosophically"), and then BERT translates that into an embedding which is then compared to embeddings of video content

(idea by [Nevan Wichers](https://github.com/wichersn))

**Comment by lenhoanglnh** [comment]
**Status**: no one is tackling this. Please feel free to take on this research project. 
We probably need more data to get this to work though.

**Comment by sergeivolodin** [comment]
One way is to train a model which maps

Natural language sentence -> (preferences vector, search string)

For example, if I type "news US" it will infer that I probably want Reliable information, and that "United States" should be in the search phrase.

To begin with this, we can start by using a hand-coded algorithm (there are not so many categories, and for each we write a heuristic), because it's not clear for me how to train a model end-to-end for this
