### ISSUE TITLE
[extension] feat: Use frontent chosen languages for extension

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#349]
- [ ] Use the languages configuration choice persisted by the frontend
- [ ] Deprecate language choice from the extension
- [ ] If no frontend, resort to default navigator.languages

**Comment by glerzing** [comment]
Do you think I should do something for the browser extension too ?
I considered adding parameters for the languages, here is how it could look like :
![Capture d’écran de 2022-01-02 11-36-08](https://user-images.githubusercontent.com/47578089/147892864-d7c2ed0c-35fe-4a47-ac75-eac5fa6c857f.png)

Another potential improvement would be in the youtube recommendations, refreshing only Tournesol recommandations when clicking in on the current language button, and not the whole page.

But I don't know if it's not more relevant for users to stick to their favorite language. What do you think ?

Besides, is it possible to load the Tournesol recommandations before Youtube recommandations? Because with a relatively slow internet, Tournesol recommandations can take a few seconds to appear, even if they are at the top. There can also be an in-between image : 
![Capture d’écran de 2022-01-03 01-15-26](https://user-images.githubusercontent.com/47578089/147893055-e780853b-8eca-4298-99bb-faf8b587e908.png)

**Comment by lfaucon** [comment]
> But I don't know if it's not more relevant for users to stick to their favorite language. And it's weird that all the menus are in english if other languages are supported. Maybe allowing only one language, and updating the menus accordingly is wiser. What do you think ?

I see this as two separate things: 1. Multiple possible languages for video recommendations; 2. One chosen language for the interface. That is quite similar to how Youtube works now (the user selects one language for the interface, but the recommendations can cover multiple languages). As for our priorities, I think point 1 is slightly more valuable to us right now and easier to implement. @amatissart has started working on point 2. for the main website (https://github.com/tournesol-app/tournesol/issues/329), maybe we could tackle the extension at the same time.

> Another potential improvement would be in the youtube recommendations, refreshing only Tournesol recommandations when clicking in on the current language button, and not the whole page.

Agreed. That's very sloppy work that I'm guilty of. Created a ticket: https://github.com/tournesol-app/tournesol/issues/404

> Besides, is it possible to load the Tournesol recommandations before Youtube recommandations? Because with a relatively slow internet, Tournesol recommandations can take a few seconds to appear, even if they are at the top. There can also be an in-between image (~ 0,5 seconds) while the tournesol recommendations are loading

Yes, this would indeed be great if recommendations can be loaded faster. We have not made much efforts to optimize anything here. I created https://github.com/tournesol-app/tournesol/issues/403 that you or someone else may work on.

**Comment by glerzing** [comment]
What do you think, @amatissart , should we dissociate the UI language and the recommandations language? And should we allow multiple recommandation languages or only the user's preferred language? To me, it looks like it adds complexity and confusion, but I'm still not sure what to do.

**Comment by lfaucon** [comment]
Note: After discussion, we are unsure how to make it work and will hold on this task for some time until we have clearer ideas
