### ISSUE TITLE
display the neutral position on the comparison page

### ISSUE THREAD

**Issue by pums974** [tournesol-app/tournesol#486]
When comparing two videos, especially when looking at the optional criterias, it can be difficult to see the neutral position.

**Comment by GresilleSiffle** [comment]
I made some UX/UI tests.

It's possible to use the Material UI [custom marks](https://mui.com/components/slider/#custom-marks) to display the neutral position, or even any position that seems relevant.

I used the digit `0` to represent the neutral position and it appears to be rather confusing. When I move the slider, there is always this `0` displayed in a fixed position, and I have the constant feeling that the slider is currently in the neutral position, even if not.

![capture](https://user-images.githubusercontent.com/39056254/151954139-4bacfa99-6004-456c-aa47-2738c3ffbcfd.png)

So I decided to use the built-in feature of the `<Slider>` component allowing to always display the current value, but the UI turns to be rather complex, and heavy. I personally found that the combination of the neutral value + the current value was still confusion. 

![capture2](https://user-images.githubusercontent.com/39056254/151954676-45da9a95-9af8-4916-9bde-c37bba3e0d8a.png)

The third option I tested, is to represent the current value in the same place of neutral value. It turns out to be more easy to read, and lighter than the other options. It's still imperfect as is, mainly because of the minus sign, but it can be easily replaced by symbols or colors ( arrow symbols like **<-** or **->** would be better than a color, as they are more friendly with colorblind people )

![capture3](https://user-images.githubusercontent.com/39056254/151955179-36bb613c-08d8-4b8c-9c12-433aa2ec6d08.png)

**Comment by GresilleSiffle** [comment]
Here is an alternative without number.

![capture4](https://user-images.githubusercontent.com/39056254/151958883-3de54c0d-aa2e-40e8-9324-8484b2de9fa2.png)

**Comment by amatissart** [comment]
I am not convinced showing the raw number would help much, especially as the scale is not defined explicitly.   
What does "8" out if 10 mean ? Does it quantify how confident I am about how the video 2 is better than video 1. Or in what extent the second video is better ? This would need to be clarified first, but that's another topic, perhaps related to #496.

Adding a larger tick on the neutral position seems to be a reasonable first step.
