### ISSUE TITLE
Extention: Rate later fail even if I'm logged

### ISSUE THREAD

**Issue by Conchylicultor** [tournesol-app/tournesol#517]
I'm logged in the https://tournesol.app/ website. Yet, whenever I click on the "Rate Later" button in a YouTube video, I got:

> Make sure you are logged in on https://tournesol.app/. If you are logged in and this error persists, please let us know by creating an issue on https://github.com/tournesol-app/tournesol

The error is not consistent. Sometimes, after a few click, the app button sudently start working. Sometimes, it does not even after refreshing the page.

**Comment by GresilleSiffle** [comment]
Hello @Conchylicultor 

Thanks for creating a ticket, and really sorry for the issue.

Which browser are you using?

We have recently fixed several issues related to the login and we plan to update the Chrome and Firefox extension very soon. Those fixes will allow the extension to automatically refresh the connection to Tournesol in the background, and will display a login form for non-logged users in case of need.

Currently the Rate Later button and the browser action [should work on Firefox](https://addons.mozilla.org/en-US/firefox/addon/tournesol-extension/) since the last update two days ago.

If I'm not mistaken the fixed Chrome/Chromium version hasn't been published yet. Can you confirm @aidanjungo ?

**Comment by aidanjungo** [comment]
I release the Firefox version on Friday evening, but I don't know when @lfaucon release the last Chrome version.

**Comment by GresilleSiffle** [comment]
Thanks Adain.

According the page of [the Tournesol Extension page of the Chrome web store](https://chrome.google.com/webstore/detail/tournesol-extension/nidimbejmadpggdgooppinedbggeacla), the currently available version of the extension is 2.0.5 ( one minor version late compared to Firefox ).

If there is no objection, we could plan an update this week.

**Comment by lfaucon** [comment]
Published 2.1.0 now (sorry for the delay). As it requires new permission (webRequest & webRequestBlocking) it may take a day to be updated in the store.

**Comment by lfaucon** [comment]
The authentication issue should be resolved once the update is publish.

**Comment by GresilleSiffle** [comment]
The new **2.1.0** version of the extension is now also available on Chrome and derivatives:
- https://chrome.google.com/webstore/detail/tournesol-extension/nidimbejmadpggdgooppinedbggeacla
