### ISSUE TITLE
refactor: create the model `Poll`

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#526]
**requires** #525 

also see the issue #509 

---

**(1)**

Create the new model `Poll`.

Fields
- `name` SlugField + unique
- `entity_type`, CharField with the same choices as the one in `Entity` 
- (question) in the future do we want an `open` field to allow / prevent comparisons to be made?
- (question) in the future do we want a boolean flag `ml` telling the ML to run on this poll or not?

Create the first poll in a migration, named `videos`.

Create a FK (can be null for now) from `Comparison` to `Poll`.

Create a FK (can be null for now) from `ContributorRating` to `Poll`.

**(2)**

**n-n** relation between `Poll` and `Criteria`
- with an additional field `rank`, used to order the field on the front end ( values could be 10, 20, 30, 40, etc. to have space for re-ordering ) 

Create the new model `Criteria`.
- `name` SlugField + unique
- `optional` boolean 

Create the new model `CriteriaLocale`.
- FK to `Criteria`
- lang CharField with choices from Django settings LANGUAGES
- label

Plan to add a validation in the API, rejecting requests that contain criteria not available in the current poll.

**(3)**

Configure the admin interface, to be able to add polls and criteria.

**Comment by lfaucon** [comment]
> (question) in the future do we want an open field to allow / prevent comparisons to be made?

Probably yes. Let's not have this field today and create it when we are ready to implement a feature using it.

> (question) in the future do we want a boolean flag ml telling the ML to run on this poll or not?

I think that would be the same thing as the `open` field. 

> Create the first poll in a migration, named videos.

I want a more fancy name to honor the original vision of Tournesol ! 🌻 

> Create a FK (can be null for now) from Comparison to Poll.
> Create a FK (can be null for now) from ContributorRating to Poll.

Is it much easier to allow null for now, instead of setting all comparisons and ratings to the "videos" Poll ? What is your reasonning for proposing this way?

> with an additional field rank, used to order the field on the front end ( values could be 10, 20, 30, 40, etc. to have space for re-ordering )
>
> Create the new model Criteria.
>
> name SlugField + unique
> optional boolean

Do I understand that `rank` is an attribute of the `Criteria` model ?

> Configure the admin interface, to be able to add polls and criteria.

The minimum that works, because it will be a very rare operation.
