### ISSUE TITLE
refactor: create the `Poll` API

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#529]
**requires** #527

also see the issue #509

---

**backend**

Create new endpoints for the polls.

All those endpoints are public.

**(1)** `GET /polls/{pollname}` to fetch all poll's information PLUS the the list of its criteria.

**(2)** `GET /polls/{pollname}/recommendations` to fetch recommendations ordered by the " Tournesol score " DESC

**(3)** `GET /polls/{pollname}/entities` to fetch all entities, regardless of the score, without any default filter (except entities are still related to the poll scope)

Add tests.

**Comment by lfaucon** [comment]
This ticket was closed without implementing the third endpoint.

Either:
1. Deemed redundant with the unsafe recommendations? In which case, let's move the ticket to DONE on the kanban
2. Planned to be implemented? in which case, let's re-open the ticket and proceed with the implementation.

I'm slightly in favor of option 2 because it is a more efficient endpoint when the extra fetching, summing and sorting of scores is not needed.

**Comment by amatissart** [comment]
When implementing the routes `GET /entities/` routes, it seemed indeed redundant to have  `GET /polls/{pollname}/entities/`. That's why it was closed in #585.

What would be a use case for this endpoint which would not be addressed by either `GET /polls/{pollname}/recommendations/?unsafe=true` (to fetch all entities scored in a poll), or `GET /entities/?type={entityType}` (to fetch all entities present in the database, including those without comparison)?

**Comment by lfaucon** [comment]
Ok 👌 moving to DONE
