### ISSUE TITLE
epic: Candidates final ranking page

### ISSUE THREAD

**Issue by amatissart** [tournesol-app/tournesol#833]
- [ ] Use `SearchFilter` with following options
  - "sort by criteria" dropdown.
  - same filter "?score_mode" as in #830 
- [ ] Use `EntityCard` with scores for each candidate, in a new `EntityList` component
  - Show "deviation" in addition to "Tournesol score"? How to represent it?

**Comment by GresilleSiffle** [comment]
Should we make the recommendation page able to display any type of entity?

**Comment by GresilleSiffle** [comment]
Here is how I see the plan:

**step 1**

Create a `RecommendationPage` that is an exactly a copy of `VideoRecommendationPage`.

Make it work with the poll API instead of the video API, and replace all occurrences of videos by entities in this new file.

**step 2**

Check how this page behaves with the candidate entity type and how much work is required to transform the `VideoList` into an `EntityList`.

An `EntityList` could be a wrapper around `VideoList` and `CandidateList`, selecting the right component according to the currently selected poll.

The list should use `EntityCard`.

**step 3**

Reconfigure the filters.

**step 4**

More?
