### ISSUE TITLE
Search index

### ISSUE THREAD

**Issue by amatissart** [tournesol-app/tournesol#902]
### Goals
* Search robust to typos, multiple words (in any order)
* Search with synonyms (optional)

### Questions
* Where to store the index?
  *  The easiest solution would be to use Postgres (single source of truth)
  * "whoosh" writes index files on disk. When are they generated?

* How to update the index, when an entity is added / updated / removed?
  * Do we need to rebuild the whole index periodically? 

* Preprocessing steps
  * tokenization / stemming / etc.
  * synonyms, with Wordnet ? at query-time? at index-time?  

* Evaluate "whoosh" to build the index.
  * Any feature that is not already implemented in PG? (https://www.postgresql.org/docs/13/textsearch.html)

* How long to build the index?

**Comment by glerzing** [comment]
> Any feature that is not already implemented in PG?

In terms of functionality, I think PostgreSQL has indeed all the needed features (indexing, weighting, synonyms...). It looks a bit rigid though, so if we want to do some advanced functionality or customization that is not directly supported, it could be a problem. 

> Where to store the index?

Django-Haystack can be used with Whoosh to store the index either in files or in PostgreSQL. But in my opinion (without much practical experience with databases), storing it in a file or temporary database element would be easier to maintain, and if the index is rebuild at startup, this would regularly clean any inconsistency between the index and the entities table. And it would make the database lighter. But I don't know yet how long it is to rebuild the whole index.

> Do we need to rebuild the whole index periodically?

No, just I guess when an entity is modified. Partial indexing is supported.

It is complicated to make a decision, but here are in my opinion the pros and cons of using PostgreSQL instead of (Django-Haystack + Whoosh) :
pros:
- less or even no dependencies if we use the PostgreSQL thesaurus
- More maintained than Django-Haystack and Whoosh
- In terms of performances, it looks like Elastic Search > PostgreSQL > Whoosh

cons:
- scalability (a benefit of Django-Haystack is that it is a common interface with multiple search engines, which facilitates migration to higher-traffic solutions, like Elastic Search)
- The Django interface in django.contrib.postgres.search looks limited, so I think it requires writing SQL. The building of the index does not look simple too.
- possibility that some advanced feature is missing or, more likely, that it does not allow enough control and customization over the index.

**Comment by glerzing** [comment]
Performances avec et sans index GIN:
[explain with GIN.txt](https://github.com/tournesol-app/tournesol/files/8952088/explain.with.GIN.txt)
[explain without GIN.txt](https://github.com/tournesol-app/tournesol/files/8952089/explain.without.GIN.txt)
[explain 2 with GIN.txt](https://github.com/tournesol-app/tournesol/files/8952090/explain.2.with.GIN.txt)
[explain 2 without GIN.txt](https://github.com/tournesol-app/tournesol/files/8952091/explain.2.without.GIN.txt)

**Comment by amatissart** [comment]
@glerzing Reading the logs more carefully, I think the difference can be explained by looking at when the "ts_rank" filter is applied:

* **"explain with GIN.txt"**: while joining "tournesol_entitycriteriascore" with "tournesol_entity"
```
->  Nested Loop  (cost=0.28..553.44 rows=16 width=240) (actual time=0.633..28.072 rows=56 loops=1)
      ->  Seq Scan on tournesol_entitycriteriascore  (cost=0.00..242.97 rows=47 width=30) (actual time=0.005..1.824 rows=9465 loops=1)
            Filter: ((poll_id = 1) AND ((score_mode)::text = 'default'::text))
      ->  Index Scan using tournesol_video_pkey on tournesol_entity  (cost=0.28..6.60 rows=1 width=206) (actual time=0.003..0.003 rows=0 loops=9465)
            Index Cond: (id = tournesol_entitycriteriascore.entity_id)
            Filter: (ts_rank(search_vector, '''racism'''::tsquery) >= '0.001'::double precision)
            Rows Removed by Filter: 1
```

* **"explain without GIN.txt"**: when filtering "tournesol_entity" first
```
->  Seq Scan on tournesol_entity  (cost=0.00..1125.70 rows=1816 width=206) (actual time=0.150..6.938 rows=12 loops=1)
      Filter: (ts_rank(search_vector, '''racism'''::tsquery) >= '0.001'::double precision)
      Rows Removed by Filter: 5435
```

But in both cases, I don't think any full-text index is used. 
Are you sure an SQL query such as 
```
WHERE (ts_rank("tournesol_entity"."search_vector", plainto_tsquery('english'::regconfig, 'racism')) >= 0.001
```
is a correct way to query the index ?

In the examples present in the PG documentation, the `@@` operator is used to write a filter between a "tsvector" and a "tsquery", with something like:
```
WHERE textsearchable_col @@ to_tsquery('search query')
```
https://www.postgresql.org/docs/13/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX

**Comment by glerzing** [comment]
I forgot to mention it, but the SQL is generated by Django. I didn't use any raw SQL. The cleaned words are stored in the database as a SearchVectorField ("search_vector").
Using ts_rank is I think the reason why it doesn't use "@@".

Anyway, don't worry with that for now, I will invite you for the PR when it is ready.

**Comment by glerzing** [comment]
You were right, @amatissart , the GIN index was not being used. I changed a bit the query type (I was filtering on the relevance score, now I pre-filter by selecting entities for which the words appear) and now it usually works.

summary of the features (check the PR #1039 for more details):
- language-specific stemming and stop-words removal
- accent-insensitive (Unaccent Postgres extension), case-insensitive
- no synonyms search
- no auto-correction
