### ISSUE TITLE
Byzantine-resilience and strategyproofness of Tournesol's algorithms

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#91]
Sadegh and I already will submit a paper soon on the Byzantine-resilience and strategyproofness of Licchavi, the machine learning framework that Tournesol is built upon. We will make it available soon.
However our assumptions fail to capture Tournesol's actual setting. Future research will have to study the more particular case of Tournesol.

**Status**: We already have many preliminary results! It's looking very good. But because we're already too busy with our current research projects, we've decided to postpone the paper, which will very likely be submitted to ICLR. We'll try to have a version on ArXiV in the coming months.

**Comment by sergeivolodin** [comment]
I'm not a specialist, but I see this possible case when it might fail:

- The utility of a single agent is to bring the global score closer to their own preferences (assumption)
- Suppose that my true preference for a pair of videos v1 and v2 on a criteria f is Q=0.3 (in -1, 1 range)
- However, the global score is now equivalent to having Q=-1 (v1 is a lot better)
- So, to maximize my own utility, I set my own Q:=1 instead of Q=0.3 (true)
