### ISSUE TITLE
Improve Criteria Bar Chart on Video Analysis page

### ISSUE THREAD

**Issue by adrausch** [tournesol-app/tournesol#933]
TODO:

- [x] Include main criteria in Bar Chart
- [x] Display scores and labels on bars
- [x] Make the chart denser (smaller images, smaller font, less space)
- [x] When clicking (or hovering?) on a criteria, changes the selected criteria on the Histogram. (Maybe always show that one criteria is selected?)

**Comment by sigmike** [comment]
> Display scores and labels on bars

I'm not sure how to do that. I made a few attempts but none of them seems satisfactory:
* adding the criteria to the left (adding them above or below doesn't seem to be possible, and adding the score on the bar doesn't seem to work reliably):
![2022-05-20_18-31](https://user-images.githubusercontent.com/28259/169572268-b2c48a50-8b54-4f62-a9e2-c493c476e584.png)
* using sliders:
![2022-05-20_17-56](https://user-images.githubusercontent.com/28259/169566527-543f7134-b8f4-4dbd-ae95-cb97edce531a.png)
* using custom made bars instead of recharts:
![2022-05-20_18-09](https://user-images.githubusercontent.com/28259/169568672-3df4d306-03a4-47f5-bfb5-95e81419970e.png)

The last 2 make the chart taller, so they don't help making the chart denser.

Any thoughts @lfaucon @adrausch @GresilleSiffle @amatissart @aidanjungo?

**Comment by amatissart** [comment]
@sigmike My preference would be for your 3rd version with the custom bars. However, personally I would find acceptable to remove the criteria names, and keep them visible on hover only. 

To make the chart denser, after some thinking, we could consider drawing the bars on this graph as a "thermometer chart", without any visible minimal bound. Compared to the current bars centered on 0, I see 2 advantages:
 * the layout would be more predictable whatever the exact scores are. The score numbers can always be displayed on the right of each bar, and the bars themselves can be made thinner.
 * it would make a clear distinction between the score 0 and the absence of score, which is not obvious with the current chart. And as we expect most scores to be close to 0, the chart would be more aesthetically pleasing.

Something like this, roughly:
![thin_bars](https://user-images.githubusercontent.com/4726554/169637826-4e86febd-b3aa-4e27-9341-8922e0227937.png)

I am not sure about the tooltips though. Maybe it would be better to use a larger tooltip with the criterion name and some explanation about the scores values?

Another idea would be to draw all bars in grey by default, except for the one that represents the criterion that is currently selected in the larger context of the analysis page:
![thin_bars3](https://user-images.githubusercontent.com/4726554/169638120-7682fedf-cddf-408d-b977-b175b6c1ec46.png)

These are just ideas of course. I am sure others will come up with other suggestions.

**Comment by aidanjungo** [comment]
Visually I like the one propose by @amatissart, but I am not a fan of having negative scores that look positive (because starting from the left). Maybe we could do a mix of this proposition with the first one of @sigmike or the same but with the criteria in the middle.

**Comment by GresilleSiffle** [comment]
In case of need, we can always go for a simple (meaning with no custom CSS or complex tweaks) `PositiveAndNegativeBarChart`.

https://recharts.org/en-US/examples/PositiveAndNegativeBarChart

**Comment by lfaucon** [comment]
Decision:

We'll implement 
https://user-images.githubusercontent.com/4726554/169637826-4e86febd-b3aa-4e27-9341-8922e0227937.png
Criteria names appear in Tooltips (similar to how they appear now)
